import {Router} from "express";
import crypto from "node:crypto";
import db from "./db.js";
export const router=Router();
export function current(req){return req.session.userId?db.prepare("SELECT * FROM users WHERE id=?").get(req.session.userId):null}
export function audit(u,type,details,botId=null){db.prepare("INSERT INTO events(actor_id,discord_id,bot_id,type,details) VALUES(?,?,?,?,?)").run(u?.id||null,u?.discord_id||null,botId,type,details)}
router.get("/discord",(req,res)=>{const state=crypto.randomBytes(24).toString('hex');req.session.state=state;const p=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID||'',response_type:'code',redirect_uri:process.env.DISCORD_REDIRECT_URI||'',scope:'identify',state});res.redirect('https://discord.com/oauth2/authorize?'+p)});
router.get("/discord/callback",async(req,res)=>{try{if(!req.query.code||req.query.state!==req.session.state)return res.status(400).send('طلب تسجيل الدخول غير صالح');const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code:req.query.code,redirect_uri:process.env.DISCORD_REDIRECT_URI});const t=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!t.ok)throw Error('OAuth token exchange failed');const tok=await t.json();const m=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${tok.access_token}`}});if(!m.ok)throw Error('Discord user lookup failed');const me=await m.json();let u=db.prepare('SELECT * FROM users WHERE discord_id=?').get(me.id);if(!u){const owner=db.prepare("SELECT 1 FROM users WHERE role='Owner' LIMIT 1").get();const role=owner?'Member':'Owner';const r=db.prepare('INSERT INTO users(discord_id,username,avatar,role) VALUES(?,?,?,?)').run(me.id,me.username,me.avatar||'',role);u=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid);audit(u,'Login',`أول دخول — ${role}`)}else{db.prepare('UPDATE users SET username=?,avatar=? WHERE id=?').run(me.username,me.avatar||'',u.id);audit(u,'Login','تسجيل دخول')}if(u.blocked)return res.status(403).send('الحساب محظور');req.session.userId=u.id;delete req.session.state;res.redirect(process.env.APP_URL||'http://localhost:5173')}catch(e){console.error(e);res.status(500).send('تعذر تسجيل الدخول عبر Discord')}})
router.get('/me',(req,res)=>{const u=current(req);if(!u)return res.status(401).json({error:'غير مسجل الدخول'});res.json({...u,permissions:JSON.parse(u.permissions||'[]')})});
router.post('/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));