import {Router} from "express";
import db,{encrypt,decrypt} from "./db.js";
import {current,audit} from "./auth.js";
import {Client,GatewayIntentBits} from "discord.js";
export const router=Router(); const clients=new Map();
const base=['ban','kick','timeout','warn','clear','logs','automod','jail','setup-staff'];
function auth(req,res,next){const u=current(req);if(!u)return res.status(401).json({error:'غير مسجل الدخول'});req.user=u;next()}
const owner=u=>u.role==='Owner';
const perms=u=>JSON.parse(u.permissions||'[]');
function allowed(u,b){return owner(u)||b.owner_id===u.id||perms(u).includes('Manage Bots')}
function safe(b){return {id:b.id,owner_id:b.owner_id,name:b.name,client_id:b.client_id,category:b.category,description:b.description,avatar:b.avatar,status:b.status,created_at:b.created_at}}
router.get('/',auth,(req,res)=>{const b=owner(req.user)?db.prepare('SELECT * FROM bots ORDER BY id DESC').all():db.prepare('SELECT * FROM bots WHERE owner_id=? ORDER BY id DESC').all(req.user.id);res.json({bots:b.map(safe),limit:owner(req.user)?null:5})});
router.post('/',auth,(req,res)=>{const {name,clientId,botToken,category,description='',avatar=''}=req.body||{};if(!name||!clientId||!botToken||!category)return res.status(400).json({error:'أكمل بيانات البوت'});if(!owner(req.user)&&db.prepare('SELECT COUNT(*) c FROM bots WHERE owner_id=?').get(req.user.id).c>=5)return res.status(400).json({error:'وصلت للحد الأقصى: 5 بوتات'});if(db.prepare('SELECT 1 FROM bots WHERE client_id=?').get(clientId))return res.status(409).json({error:'هذا البوت مضاف مسبقًا'});const r=db.prepare('INSERT INTO bots(owner_id,name,client_id,token,category,description,avatar) VALUES(?,?,?,?,?,?,?)').run(req.user.id,name,clientId,encrypt(botToken),category,description,avatar);db.prepare('INSERT INTO bot_settings(bot_id) VALUES(?)').run(r.lastInsertRowid);for(const n of base)db.prepare('INSERT INTO commands(bot_id,name,response) VALUES(?,?,?)').run(r.lastInsertRowid,n,`تم تنفيذ ${n}`);const b=db.prepare('SELECT * FROM bots WHERE id=?').get(r.lastInsertRowid);audit(req.user,'Bot Added',`إضافة ${name}`,b.id);res.status(201).json({bot:safe(b)})});
router.get('/:id',auth,(req,res)=>{const b=db.prepare('SELECT * FROM bots WHERE id=?').get(req.params.id);if(!b||!allowed(req.user,b))return res.status(404).json({error:'البوت غير موجود أو لا تملك صلاحية'});const s=db.prepare('SELECT * FROM bot_settings WHERE bot_id=?').get(b.id);const c=db.prepare('SELECT id,name,enabled,required_role,required_permission,response,error_message,cooldown,logs,allowed_channels,custom FROM commands WHERE bot_id=? ORDER BY custom,name').all(b.id);res.json({bot:safe(b),settings:s,commands:c})});
router.patch('/:id',(req,res)=>{const u=current(req);const b=db.prepare('SELECT * FROM bots WHERE id=?').get(req.params.id);if(!u||!b||!allowed(u,b))return res.status(403).json({error:'غير مصرح'});const fs=['name','category','description','avatar'],set=[],v=[];for(const f of fs)if(req.body?.[f]!==undefined){set.push(f+'=?');v.push(req.body[f])}if(set.length){v.push(b.id);db.prepare(`UPDATE bots SET ${set.join(',')} WHERE id=?`).run(...v);audit(u,'Bot Updated','تحديث بيانات البوت',b.id)}res.json({ok:true})});
router.delete('/:id',(req,res)=>{const u=current(req),b=db.prepare('SELECT * FROM bots WHERE id=?').get(req.params.id);if(!u||!b||!allowed(u,b))return res.status(403).json({error:'غير مصرح'});const c=clients.get(b.id);if(c)c.destroy();db.prepare('DELETE FROM bots WHERE id=?').run(b.id);audit(u,'Bot Removed','حذف البوت',b.id);res.json({ok:true})});
router.patch('/:id/settings',(req,res)=>{const u=current(req),b=db.prepare('SELECT * FROM bots WHERE id=?').get(req.params.id);if(!u||!b||!allowed(u,b))return res.status(403).json({error:'غير مصرح'});db.prepare('UPDATE bot_settings SET prefix=?,settings=? WHERE bot_id=?').run(req.body.prefix||'-',JSON.stringify(req.body.settings||{}),b.id);audit(u,'Settings Changed','تغيير إعدادات البوت',b.id);res.json({ok:true})});
router.patch('/:id/commands/:cid',(req,res)=>{const u=current(req),b=db.prepare('SELECT * FROM bots WHERE id=?').get(req.params.id),c=db.prepare('SELECT * FROM commands WHERE id=? AND bot_id=?').get(req.params.cid,req.params.id);if(!u||!b||!c||!allowed(u,b))return res.status(403).json({error:'غير مصرح'});const fs=['name','enabled','required_role','required_permission','response','error_message','cooldown','logs','allowed_channels'],set=[],v=[];for(const f of fs)if(req.body?.[f]!==undefined){set.push(f+'=?');v.push(req.body[f])}if(set.length){v.push(c.id);db.prepare(`UPDATE commands SET ${set.join(',')} WHERE id=?`).run(...v);audit(u,'Command Changed',`تعديل ${c.name}`,b.id)}res.json({ok:true})});
router.post('/:id/commands',(req,res)=>{const u=current(req),b=db.prepare('SELECT * FROM bots WHERE id=?').get(req.params.id);if(!u||!b||!allowed(u,b))return res.status(403).json({error:'غير مصرح'});try{const r=db.prepare('INSERT INTO commands(bot_id,name,response,required_role,required_permission,cooldown,allowed_channels,custom) VALUES(?,?,?,?,?,?,?,1)').run(b.id,req.body.name,req.body.response||'',req.body.required_role||'',req.body.required_permission||'',req.body.cooldown||0,req.body.allowed_channels||'');audit(u,'Command Changed','إضافة أمر مخصص',b.id);res.status(201).json({id:r.lastInsertRowid})}catch{res.status(409).json({error:'الأمر موجود مسبقًا'})}});
router.delete('/:id/commands/:cid',(req,res)=>{const u=current(req),b=db.prepare('SELECT * FROM bots WHERE id=?').get(req.params.id),c=db.prepare('SELECT * FROM commands WHERE id=? AND bot_id=?').get(req.params.cid,req.params.id);if(!u||!b||!c||!c.custom||!allowed(u,b))return res.status(403).json({error:'غير مصرح'});db.prepare('DELETE FROM commands WHERE id=?').run(c.id);audit(u,'Command Changed','حذف أمر مخصص',b.id);res.json({ok:true})});
async function start(b){if(clients.has(b.id))return;const c=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});c.once('ready',()=>db.prepare("UPDATE bots SET status='online' WHERE id=?").run(b.id));c.on('error',()=>db.prepare("UPDATE bots SET status='error' WHERE id=?").run(b.id));c.on('messageCreate',async m=>{if(m.author.bot||!m.guild)return;const s=db.prepare('SELECT prefix FROM bot_settings WHERE bot_id=?').get(b.id),p=s?.prefix||'-';if(!m.content.startsWith(p))return;const a=m.content.slice(p.length).trim().split(/\s+/),n=(a.shift()||'').toLowerCase(),cmd=db.prepare('SELECT * FROM commands WHERE bot_id=? AND name=? AND enabled=1').get(b.id,n);if(cmd&&cmd.response)await m.reply(cmd.response.replaceAll('{user}',m.author.toString()).replaceAll('{username}',m.author.username).replaceAll('{args}',a.join(' '))).catch(()=>{})});try{await c.login(decrypt(b.token));clients.set(b.id,c)}catch(e){db.prepare("UPDATE bots SET status='error' WHERE id=?").run(b.id);console.error('Bot connection failed:',e.message)}}
export async function startAll(){for(const b of db.prepare('SELECT * FROM bots').all())await start(b)}