import 'dotenv/config';
import express from 'express';
import session from 'express-session';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import path from 'node:path';
import {authRouter} from './auth.js';
import {router as botRouter,startAll} from './bots.js';
import {router as adminRouter} from './admin.js';
import './db.js';
if(!process.env.SESSION_SECRET||!process.env.ENCRYPTION_KEY)throw Error('SESSION_SECRET and ENCRYPTION_KEY are required');
const app=express();
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:process.env.APP_URL||'http://localhost:5173',credentials:true}));
app.use(cookieParser());app.use(express.json({limit:'1mb'}));app.use(morgan('tiny'));
app.use(session({secret:process.env.SESSION_SECRET,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000}}));
app.use('/api/auth',authRouter);app.use('/api/bots',botRouter);app.use('/api/admin',adminRouter);
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Hola Bots'}));
const dist=path.resolve('client/dist');app.use(express.static(dist));app.get('/{*splat}',(req,res)=>req.path.startsWith('/api/')?res.status(404).json({error:'Not found'}):res.sendFile(path.join(dist,'index.html')));
const port=Number(process.env.PORT||3000);app.listen(port,()=>{console.log('Hola Bots:',port);startAll().catch(console.error)});