import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{BrowserRouter,useLocation,useNavigate,useParams,Link}from'react-router-dom';import'./style.css';
const api=async(u,o={})=>{const r=await fetch(u,{credentials:'include',headers:{'Content-Type':'application/json',...(o.headers||{})},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'حدث خطأ');return d};
const cats={System:'إدارة السيرفر',Security:'حماية السيرفر',Ticket:'التذاكر',Welcome:'الترحيب',Music:'الموسيقى'};
function Shell({u,children}){return <div className="app"><aside><div className="brand"><b>H</b><div><strong>Hola Bots</strong><small>لوحة تحكم البوتات</small></div></div><nav><Link to="/dashboard">الرئيسية</Link><Link to="/bots">البوتات</Link>{u.role==='Owner'&&<><i>الإدارة</i><Link to="/owner/users">المستخدمون</Link><Link to="/owner/monitoring">المراقبة</Link><Link to="/owner/warnings">التحذيرات</Link><Link to="/owner/logs">سجل العمليات</Link></>}</nav><div className="user">{u.username}<small>{u.role}</small></div></aside><main>{children}</main></div>}
function Login(){return <div className="login"><section><div className="logo">H</div><h1>Hola Bots</h1><p>لوحة تحكم عربية لإدارة بوتات Discord التي تملكها</p><a href="/api/auth/discord">تسجيل الدخول عبر Discord</a></section></div>}
function App(){const[u,setU]=useState();const l=useLocation();useEffect(()=>api('/api/auth/me').then(setU).catch(()=>setU(null)),[]);if(u===undefined)return <div className="loading">جاري التحميل…</div>;if(!u)return <Login/>;if(l.pathname==='/bots')return <Bots u={u}/>;if(l.pathname.startsWith('/bots/'))return <Bot u={u}/>;if(l.pathname.startsWith('/owner/'))return <Owner u={u} type={l.pathname.split('/')[2]}/>;return <Home u={u}/>}
function Home({u}){const[b,setB]=useState([]);useEffect(()=>api('/api/bots').then(x=>setB(x.bots)),[]);return <Shell u={u}><Header title={u.username} sub="نظرة سريعة على بوتاتك ونشاطك."/><div className="stats"><Stat n={b.length} t="البوتات"/><Stat n={u.role==='Owner'?'غير محدود':'5'} t="الحد المسموح"/><Stat n={b.filter(x=>x.status==='online').length} t="متصل الآن"/></div><h2>بوتاتك</h2>{b.length?<div className="grid">{b.map(x=><Card b={x}/>)}</div>:<Empty/>}</Shell>}
function Header({title,sub}){return <header><div><small>Hola Bots</small><h1>{title}</h1><p>{sub}</p></div><Link className="btn" to="/bots">+ إضافة بوت</Link></header>}
function Stat({n,t}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
function Card({b}){return <Link className="card" to={'/bots/'+b.id}><div className="botimg">{b.avatar?<img src={b.avatar}/>:b.name[0]}</div><div><h3>{b.name}</h3><p>{cats[b.category]||b.category}</p><small>{b.description||'بدون وصف'} · <em className={b.status}>{b.status==='online'?'متصل':'غير متصل'}</em></small></div></Link>}
function Empty(){return <div className="empty"><div>+</div><h2>ما أضفت أي بوت حتى الآن</h2><p>أضف أول بوت Discord تملكه للبدء.</p><Link className="btn" to="/bots">+ إضافة بوت</Link></div>}
function Bots({u}){const[b,setB]=useState([]),[show,setShow]=useState(false);const load=()=>api('/api/bots').then(x=>setB(x.bots));useEffect(load,[]);return <Shell u={u}><Header title="إدارة البوتات" sub={u.role==='Owner'?'عدد غير محدود من البوتات.':'حتى 5 بوتات.'}/><div className="grid">{b.map(x=><Card b={x}/>)}</div>{!b.length&&<Empty/>}<button className="float btn" onClick={()=>setShow(true)}>+ إضافة بوت</button>{show&&<Add close={()=>setShow(false)} done={load}/>}</Shell>}
function Add({close,done}){const[f,setF]=useState({name:'',clientId:'',botToken:'',category:'System',description:'',avatar:''}),[e,setE]=useState('');const put=(k,v)=>setF({...f,[k]:v});async function go(x){x.preventDefault();try{await api('/api/bots',{method:'POST',body:JSON.stringify(f)});done();close()}catch(z){setE(z.message)}}return <div className="overlay"><form className="modal" onSubmit={go}><h2>إضافة بوت</h2>{e&&<div className="error">{e}</div>}{[['اسم البوت','name'],['Client ID','clientId'],['Bot Token','botToken'],['الوصف','description'],['رابط الصورة','avatar']].map(([l,k])=><label>{l}<input type={k==='botToken'?'password':'text'} value={f[k]} onChange={x=>put(k,x.target.value)}/></label>)}<label>القسم<select value={f.category} onChange={x=>put('category',x.target.value)}>{Object.keys(cats).map(x=><option>{x}</option>)}</select></label><div className="actions"><button type="button" onClick={close}>إلغاء</button><button className="btn">إضافة البوت</button></div></form></div>}
function Bot({u}){const{id}=useParams(),[d,setD]=useState(),[tab,setTab]=useState('overview');useEffect(()=>api('/api/bots/'+id).then(setD).catch(()=>{}),[id]);if(!d)return <Shell u={u}><div className="loading">جاري التحميل…</div></Shell>;const tabs=['overview','commands','permissions','moderation','security','automod','logs','staff','jail','settings'];return <Shell u={u}><Link to="/bots" className="back">البوتات /</Link><div className="bothead"><div className="botimg big">{d.bot.avatar?<img src={d.bot.avatar}/>:d.bot.name[0]}</div><div><h1>{d.bot.name}</h1><p>{d.bot.description||'بدون وصف'} · {d.bot.status}</p></div></div><div className="tabs">{tabs.map(x=><button className={tab===x?'sel':''} onClick={()=>setTab(x)}>{({overview:'نظرة عامة',commands:'الأوامر',permissions:'الصلاحيات',moderation:'الإدارة',security:'الحماية',automod:'AutoMod',logs:'السجلات',staff:'Staff',jail:'السجن',settings:'الإعدادات'})[x]}</button>)}</div>{tab==='overview'?<Overview d={d}/>:tab==='commands'?<Commands d={d}/>:<div className="panel"><h2>إعدادات {tab}</h2><p>قسم مستقل لهذا البوت ضمن بنية Hola Bots.</p></div>}</Shell>}
function Overview({d}){return <div className="three"><div className="panel"><h3>معلومات البوت</h3><p>اسم البوت: <b>{d.bot.name}</b></p><p>Client ID: <b>{d.bot.client_id}</b></p><p>القسم: <b>{d.bot.category}</b></p></div><div className="panel"><h3>Prefix</h3><strong className="huge">{d.settings.prefix}</strong><p>البادئة الحالية للأوامر.</p></div><div className="panel"><h3>الأوامر</h3><strong className="huge">{d.commands.length}</strong><p>أمر محفوظ.</p></div></div>}
function Commands({d}){const[c,setC]=useState(d.commands),[edit,setEdit]=useState();const save=async()=>{await api(`/api/bots/${d.bot.id}/commands/${edit.id}`,{method:'PATCH',body:JSON.stringify(edit)});setC(c.map(x=>x.id===edit.id?edit:x));setEdit(null)};return <div><div className="section"><div><h2>الأوامر</h2><p>كل أمر مستقل ويمكن تعديل إعداداته.</p></div></div>{c.map(x=><div className="cmd"><div><b>-{x.name}</b><span>{x.response||'بدون رد'}</span></div><div><button onClick={()=>api(`/api/bots/${d.bot.id}/commands/${x.id}`,{method:'PATCH',body:JSON.stringify({enabled:x.enabled?0:1})}).then(()=>setC(c.map(y=>y.id===x.id?{...y,enabled:y.enabled?0:1}:y)))}>{x.enabled?'مفعل':'معطل'}</button><button onClick={()=>setEdit({...x})}>تعديل</button></div></div>)}{edit&&<div className="overlay"><div className="modal"><h2>تعديل -{edit.name}</h2><label>اسم الأمر<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>الرد<input value={edit.response} onChange={e=>setEdit({...edit,response:e.target.value})}/></label><label>الرتبة المطلوبة<input value={edit.required_role} onChange={e=>setEdit({...edit,required_role:e.target.value})}/></label><label>الصلاحية المطلوبة<input value={edit.required_permission} onChange={e=>setEdit({...edit,required_permission:e.target.value})}/></label><label>Cooldown<input type="number" value={edit.cooldown} onChange={e=>setEdit({...edit,cooldown:Number(e.target.value)})}/></label><div className="actions"><button onClick={()=>setEdit(null)}>إلغاء</button><button className="btn" onClick={save}>حفظ</button></div></div></div>}</div>}
function Owner({u,type}){const[end,setEnd]=useState(type==='users'?'/api/admin/users':type==='monitoring'?'/api/admin/events':'/api/admin/warnings'),[d,setD]=useState([]);useEffect(()=>api(end).then(setD),[end]);const title=type==='users'?'المستخدمون':type==='monitoring'?'المراقبة':type==='warnings'?'التحذيرات':'سجل العمليات';return <Shell u={u}><Header title={title} sub="قسم الإدارة الخاص بالـOwner."/><div className="table"><table><thead><tr>{type==='users'?<><th>المستخدم</th><th>Discord ID</th><th>الرتبة</th><th>الحالة</th></>:type==='monitoring'?<><th>المستخدم</th><th>العملية</th><th>التفاصيل</th><th>التاريخ</th></>:<><th>المستخدم</th><th>السبب</th><th>الحالة</th><th>التاريخ</th></>}</tr></thead><tbody>{d.map(x=><tr>{type==='users'?<><td>{x.username}</td><td>{x.discord_id}</td><td>{x.role}</td><td>{x.blocked?'محظور':'نشط'}</td></>:type==='monitoring'?<><td>{x.username||x.discord_id}</td><td>{x.type}</td><td>{x.details}</td><td>{x.created_at}</td>:<><td>{x.user_discord_id}</td><td>{x.reason}</td><td>{x.status}</td><td>{x.created_at}</td>}</tr>)}</tbody></table></div></Shell>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);